#!/bin/bash

### Debian LXC (Linux Container) automatic creation 
### The bash script tale two arguments : 
###  First argument = hostanme
###  Second argument = IP address

### Written by Sabri Khemissa <sabri.khemissa@gmail.com

### This bash script is distributed under the license terms of the GNU GPL v3.

DIRECTORY=/var/cache/lxc/debian/
LXCDIR=/var/lib/lxc

if [ ! -d "$DIRECTORY" ]
then
  # Control will enter here if $DIRECTORY doesn't exist.
	echo "No cache available for $DIRECTORY"
	exit 1
fi

if [ ! -d "$LXCDIR" ]
then
  # Control will enter here if $DIRECTORY doesn't exist.
        echo "No lxc container directory $LXCDIR"
        exit 1
fi

if [ -d "$LXCDIR/$1" ]
then
  # Control will enter here if $DIRECTORY doesn't exist.
        echo "Container name exist change name or run : rm -rf $LXCDIR/$1"
        exit 1
fi

if [ -z $1 ]
then
	echo "add first argument"
	exit 1
elif [ -z $2 ]
then
	echo "add second argument"
	exit 1
fi

echo ""
regex="\b(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b"

CHECK=$(echo $2 | egrep $regex)

if [[ ! "$?" -eq 0 ]]
then
	echo "Incorrect IP address format!!"
	exit 1
fi

echo "-"
echo ""
echo "Great! Prerequisites are OK !"
echo ""
echo "Start building the container"
echo ""

lxc-create -n $1 -t debian

if [ ! -d "$LXCDIR/$1" ]
then
        echo "Does the container created in $LXC/$1"
        exit 1
fi

if [ ! -f "$LXCDIR/$1/config" ]
then
	echo "File not exist " $LXCDIR/$1/config
	exit 1
fi

mv $LXCDIR/$1/config $LXCDIR/$1/config.old

#to be adapted to your LCX environment
echo ""
echo "Generating configuration file in $LXCDIR/$1/config"
echo ""
echo "#generated by automation script" >> $LXCDIR/$1/config
echo "lxc.rootfs = /var/lib/lxc/$1/rootfs" >> $LXCDIR/$1/config
echo "lxc.rootfs.backend = dir" >> $LXCDIR/$1/config
echo "lxc.include = /usr/share/lxc/config/debian.common.conf" >> $LXCDIR/$1/config
echo "lxc.tty = 4" >> $LXCDIR/$1/config
echo "lxc.utsname = $1" >> $LXCDIR/$1/config
echo "lxc.arch = amd64" >> $LXCDIR/$1/config
echo "lxc.network.type = veth" >> $LXCDIR/$1/config
echo "lxc.network.flags = upl" >> $LXCDIR/$1/config
echo "lxc.network.link = lxcbr0" >> $LXCDIR/$1/config
echo "lxc.network.name = eth0" >> $LXCDIR/$1/config
echo "lxc.network.ipv4 = $2/24" >> $LXCDIR/$1/config
echo "lxc.network.ipv4.gateway = 192.168.0.1" >> $LXCDIR/$1/config

#update container networing
echo ""
echo "---"
echo ""
echo "Update network configuration"
echo ""

NETDIR=$LXCDIR/$1/rootfs/etc/network

if [ ! -f "$NETDIR/interfaces" ]
then
        echo "File not exist " $NETDIR/interfaces
        exit 1
fi

mv $NETDIR/interfaces $NETDIR/interfaces.old

echo "auto lo" >> $NETDIR/interfaces
echo "iface lo inet loopback" >> $NETDIR/interfaces
echo ""
echo "allow-hotplug eth0" >> $NETDIR/interfaces
echo "auto eth0" >> $NETDIR/interfaces
echo "iface eth0 inet static" >> $NETDIR/interfaces
echo "        address $2" >> $NETDIR/interfaces
echo "        netmask 255.255.255.0" >> $NETDIR/interfaces
echo "        gateway 192.168.0.1" >> $NETDIR/interfaces

echo "Done !"
echo ""
echo "--"
echo ""
lxc-start -n $1 -d
echo ""
echo "The container $1 is ready"
echo ""
echo "IP address $2"
echo ""
echo "Enjoy !"
echo ""
echo "Don't forget "
echo " 1. connect to the console : lxc-attach -n $1"
echo " 2. update the system : apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y dist-upgrade && sudo apt -y autoremove && apt-get clean -y"
echo " 3. change root password : passwd"
echo " 4. create user : adduser [user]"
echo ""
echo "________________"
